name: Azure Login sample workflow azureLoginWorkflow.yml

on: [push]

jobs:
  test-azure-login:
    runs-on: ubuntu-latest

    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az account show